### ISSUE TITLE
StringField with choice argument causing problem.

### ISSUE THREAD

**Issue by haridas** [stephrdev/django-mongoforms#13]
I found that inside the StringField  generator function, it is zipping the choice data and makeing it a copy. This results in to a  dictionary with non string key. This will throw an error if we convert a dictionary of non string key to json format.

 It's worked form if I'm removing the zip statement from the Field generation function of StringField.

Thank you,
haridas N.

**Comment by lig** [comment]
@haridas could you please provide exact steps to reproduce this problem?

**Comment by haridas** [comment]
Hi,

Please check this diff. I fixed this and sent a pull request also. Actually it's a very small bug. https://github.com/haridas/django-mongoforms/commit/6c762b17a6b8c35c6b2f2ac36bb19607fc552019

Regards,
Haridas N.

**Comment by lig** [comment]
Still need failing code example for testing.

**Comment by lig** [comment]
Fix merged in master
https://github.com/stephrdev/django-mongoforms/commit/5013a07851916d976415213e9fac3b969f74cf37

Thank you for reporting this issue!

Feel free to report any futher issues you will find.
