### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by v** [stephrdev/django-mongoforms#15]
When I installed this on my machine, the package didn't seem to set itself up correctly.

I ran:

`python setup.py install`

to install my application. But it looks like my `/usr/lib/python2.6/dist-packages` directory only contains a `django_mongoforms-0.2-py2.7.egg` folder.  I expect it to contain a `mongoforms/` folder as well. The mongoforms folder is hidden in the `django_mongoforms-0.2-py2.7.egg` folder.

Is this an issue with my installation or an issue with the packaging?

Thanks.

**Comment by lig** [comment]
Please provide the output of the following command:

```
python -c "import mongoforms"
```

Also I need to note that `mongoforms` installation directory is usally located under `/usr/lib/python2.6/site-packages`.

**Comment by lig** [comment]
unable to reproduce
