### ISSUE TITLE
No way to create hidden fields

### ISSUE THREAD

**Issue by justincy** [stephrdev/django-mongoforms#16]
Is there a way to create hidden input fields?

**Comment by lig** [comment]
Hello Justincy!

You can create hidden field using mongoforms in a way similar to the one you can do it using Django's native modelforms.

Just use `as_hidden` field property.

``` html
<form>
{{ form.regular_field }}
{{ form.hidden_field.as_hidden }}
</form>
```

**Comment by lig** [comment]
closing as answered
