### ISSUE TITLE
Build-in froms

### ISSUE THREAD

**Issue by PhoenixAndMachine** [stephrdev/django-mongoforms#18]
Is there any build-in forms, such as for registering and login forms?

**Comment by lig** [comment]
No there is no built in forms included with django-mongoforms.

There is [django-registration-me](https://github.com/lig/django-registration-me) project that is the complete solution for Django/Mongoengine setup based on [django-registration](https://bitbucket.org/ubernostrum/django-registration/) including all the forms you are interested in ([forms.py](https://github.com/lig/django-registration-me/blob/master/registration/forms.py)).

**Comment by PhoenixAndMachine** [comment]
Thanks, I am checking. :)
